// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tjv729qkWJYohlkoqQvziZCEpN91Jcs',
    appId: '1:388632511078:web:cc14820e8a6a33b888a3a7',
    messagingSenderId: '388632511078',
    projectId: 'kamikami-af5fe',
    authDomain: 'kamikami-af5fe.firebaseapp.com',
    storageBucket: 'kamikami-af5fe.firebasestorage.app',
    measurementId: 'G-FTZ57XXG4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkOkTmAtczkC1wCvAfLAtkdaIFt2skXM4',
    appId: '1:388632511078:android:b62e5209983818f688a3a7',
    messagingSenderId: '388632511078',
    projectId: 'kamikami-af5fe',
    storageBucket: 'kamikami-af5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIG3oKQNCTI9ZdSOeTfhVFHmIKCBR7f5Q',
    appId: '1:388632511078:ios:0670dca8310b412988a3a7',
    messagingSenderId: '388632511078',
    projectId: 'kamikami-af5fe',
    storageBucket: 'kamikami-af5fe.firebasestorage.app',
    iosBundleId: 'com.example.kamiDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIG3oKQNCTI9ZdSOeTfhVFHmIKCBR7f5Q',
    appId: '1:388632511078:ios:0670dca8310b412988a3a7',
    messagingSenderId: '388632511078',
    projectId: 'kamikami-af5fe',
    storageBucket: 'kamikami-af5fe.firebasestorage.app',
    iosBundleId: 'com.example.kamiDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8tjv729qkWJYohlkoqQvziZCEpN91Jcs',
    appId: '1:388632511078:web:bdf56aca6e70aa8e88a3a7',
    messagingSenderId: '388632511078',
    projectId: 'kamikami-af5fe',
    authDomain: 'kamikami-af5fe.firebaseapp.com',
    storageBucket: 'kamikami-af5fe.firebasestorage.app',
    measurementId: 'G-MQ30MLF076',
  );
}
